#!/usr/bin/env node
"use strict";
// vim: set ft=javascript:

var fs        = require('fs');
var path      = require('path');
var Bundler   = require('./index').Bundler;
var optimist  = require('optimist')
      .usage('Usage: xcss [options] entry')
      .option('h', {
        alias: 'help',
        boolean: true,
        describe: 'Show this message and exit'
      })
      .option('v', {
        alias: 'version',
        boolean: true,
        describe: 'Print xcss version and exit'
      })
      .option('d', {
        alias: 'debug',
        boolean: true,
        describe: 'Emit source maps'
      })
      .option('c', {
        alias: 'compress',
        boolean: true,
        describe: 'Compress output'
      })
      .option('w', {
        alias: 'watch',
        describe: 'Watch for changes and rebuild (-o/--output should be provided)'
      })
      .option('o', {
        alias: 'output',
        describe: 'Output for bundle'
      })
      .option('class-map', {
        describe: 'Use class map to remove unused stylesheet rules'
      })
      .option('t', {
        alias: 'transform',
        describe: 'Apply transform'
      });

function error(msg, showHelp) {
  if (showHelp)
    optimist.showHelp();
  console.warn('error:', msg);
  if (msg.stack)
    console.warn(msg.stack);
  process.exit(1);
}

function pipe(a, b) {
  a.on('error', function(err) {
    error(err);
  });
  a.pipe(b);
}

var cwd = process.cwd();
var argv = optimist.argv;

if (argv['class-map']) {
  var filename = argv['class-map'],
      source = fs.readFileSync(argv['class-map'], 'utf8');
  if (/\.json$/.exec(filename)) {
    argv.classMap = JSON.parse(source)
  } else {
    var findClassMap  = require('./classmap').find;
    argv.classMap = findClassMap(source).map;
  }
}

if (argv.help)
  return optimist.showHelp();

if (argv.version)
  return console.log(require('./package.json').version);

if (argv._.length === 0)
  error('provide bundle entry module as an argument', true);

var output = argv.output ? fs.createWriteStream(argv.output) : process.stdout;
var bundler = new Bundler(argv._[0], argv);

function bundle(filename) {
  if (filename) {
    filename = path.relative(cwd, filename);
    console.log('changed detected in ' + filename + ', rebuilding...');
  }
  pipe(bundler.toStream(), output);
}

bundle();

if (argv.watch) {
  if (!argv.output)
    error('provide output with -o/--output command line option');
  bundler.on('update', bundle);
}

